steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/thesisproject1859/react', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/thesisproject1859/react']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'react', '--image', 'gcr.io/thesisproject1859/react', '--region', 'us-central1', '--expose', '3000', '--platform', 'managed', '--allow-unauthenticated']
